# Generated by Django 5.0.7 on 2024-12-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_course_question_lesson_page_answer_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='video',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
    ]
