# Generated by Django 5.0.7 on 2025-01-01 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_page_video_alter_lesson_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='home.product'),
            preserve_default=False,
        ),
    ]
