# Generated by Django 5.1.7 on 2025-04-23 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='description',
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.FloatField(default=0.0)),
                ('quiz_score', models.FloatField(default=0.0)),
                ('test_score', models.FloatField(default=0.0)),
                ('overall_score', models.FloatField(default=0.0)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('badge', models.CharField(blank=True, max_length=100, null=True)),
                ('certificate_url', models.URLField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='enrolled_courses',
            field=models.ManyToManyField(through='home.Enrollment', to='home.product'),
        ),
    ]
