# Generated by Django 5.1.7 on 2025-04-23 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_profile_description_enrollment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.profile'),
        ),
    ]
