# Generated by Django 5.1.7 on 2025-07-12 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_contentcount_quizsubmission_testsubmission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='content',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.contentcount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='content',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.contentcount'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='quizsubmission',
            unique_together={('profile', 'content')},
        ),
        migrations.AlterUniqueTogether(
            name='testsubmission',
            unique_together={('profile', 'content')},
        ),
    ]
