# Generated by Django 5.1.7 on 2025-07-18 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_quiz_content_test_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.contentcount'),
        ),
        migrations.AlterField(
            model_name='contentcount',
            name='content_type',
            field=models.CharField(choices=[('page', 'Pages'), ('quiz', 'Quiz'), ('test', 'Test'), ('video', 'Video')], max_length=10),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.contentcount'),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.contentcount'),
        ),
        migrations.AlterField(
            model_name='test',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.contentcount'),
        ),
        migrations.AlterField(
            model_name='testsubmission',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.contentcount'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.contentcount'),
        ),
    ]
